from __future__ import annotations

# Catalogo fornecido pelo time comercial. Cada termo e uma consulta textual.
# Tupla: identificador interno, rotulo do nicho, termos de busca, tipo Places opcional.
NICHE_CATALOG: tuple[tuple[str, str, tuple[str, ...], str | None], ...] = (
    ('moveis_planejados_marcenaria', 'MÓVEIS PLANEJADOS / MARCENARIA', ('Marceneiro', 'Moveleiro', 'Fabricante de móveis', 'Fornecedor de móveis', 'Loja de móveis', 'Loja de móveis para cozinha', 'Loja de móveis para escritório', 'Oficina de conserto de móveis',), None),
    ('esquadrias_aluminio', 'ESQUADRIAS / ALUMÍNIO', ('Fornecedor de esquadrias de alumínio', 'Fornecedor de alumínio', 'Serralheiro', 'Serralheria', 'Empreiteiro de estruturas de aço', 'Empreiteiro de aço e ferro', 'Fabricante de aço',), None),
    ('vidracaria', 'VIDRAÇARIA', ('Vidraçaria', 'Loja de vidros', 'Loja de vidros e espelhos', 'Serviço de instalação de janelas', 'Fornecedor de janelas', 'Fornecedor de portas', 'Fabricante de vidro',), None),
    ('reformas', 'REFORMAS', ('Empreiteiro', 'Empreiteiro de reformas', 'Empreiteiro geral', 'Empresa de construção', 'Construtora', 'Empreiteiro de construção de interiores', 'Empreiteiro de instalação de interiores', 'Serviço de restauração de edifícios', 'Reformas',), None),
    ('pintura', 'PINTURA', ('Pintor', 'Empresa de pintura', 'Empreiteiro de pintura',), None),
    ('gesso_drywall', 'GESSO / DRYWALL', ('Empreiteiro de drywall', 'Fornecedor de drywall', 'Gesseiro', 'Empreiteiro de estuque', 'Empreiteiro de construção de interiores',), None),
    ('eletrica', 'ELÉTRICA', ('Eletricista', 'Serviço de instalação elétrica', 'Empresa de engenharia elétrica', 'Empreiteiro elétrico', 'Engenheiro eletricista', 'Serviço de reparos elétricos',), None),
    ('hidraulica_encanador', 'HIDRÁULICA / ENCANADOR', ('Encanador', 'Empresa de serviços hidráulicos', 'Empreiteiro hidráulico', 'Loja de materiais hidráulicos',), None),
    ('caca_vazamento', 'CAÇA-VAZAMENTO', ('Encanador', 'Serviço de detecção de vazamentos', 'Empresa de serviços hidráulicos',), None),
    ('desentupidora', 'DESENTUPIDORA', ('Serviço de limpeza de fossas', 'Encanador', 'Serviço de saneamento', 'Serviço de limpeza de esgoto',), None),
    ('dedetizacao', 'DEDETIZAÇÃO', ('Dedetizadora', 'Serviço de controle de pragas', 'Controle de pragas',), None),
    ('ar_condicionado_climatizacao', 'AR-CONDICIONADO / CLIMATIZAÇÃO', ('Empresa de climatização', 'Empreiteiro de ar condicionado', 'Serviço de conserto de ar-condicionado', 'Fornecedor de sistemas de ar condicionado', 'Empreiteiro de aquecimento', 'Empresa de refrigeração',), None),
    ('refrigeracao_comercial', 'REFRIGERAÇÃO COMERCIAL', ('Empresa de refrigeração', 'Serviço de conserto de refrigeradores', 'Fornecedor de equipamentos de refrigeração comercial', 'Empreiteiro de ar condicionado',), None),
    ('energia_solar', 'ENERGIA SOLAR', ('Empresa de energia solar', 'Fornecedor de equipamentos de energia solar', 'Empreiteiro de energia solar', 'Fornecedor de equipamentos para energia solar',), None),
    ('impermeabilizacao', 'IMPERMEABILIZAÇÃO', ('Empresa de impermeabilização', 'Empreiteiro de impermeabilização', 'Serviço de impermeabilização',), None),
    ('higienizacao_de_estofados', 'HIGIENIZAÇÃO DE ESTOFADOS', ('Serviço de limpeza de estofados', 'Serviço de limpeza', 'Serviço de limpeza de carpetes',), None),
    ('limpeza_residencial_comercial', 'LIMPEZA RESIDENCIAL / COMERCIAL', ('Serviço de limpeza', 'Empresa de limpeza', 'Serviço de limpeza doméstica', 'Serviço de limpeza comercial', 'Serviço de zeladoria',), None),
    ('limpeza_pos_obra', 'LIMPEZA PÓS-OBRA', ('Serviço de limpeza', 'Empresa de limpeza', 'Serviço de limpeza comercial', 'Serviço de zeladoria',), None),
    ('telhados', 'TELHADOS', ('Empreiteiro de telhados', 'Fornecedor de materiais para telhados', 'Serviço de reparação de telhados', 'Empresa de coberturas',), None),
    ('calhas', 'CALHAS', ('Serviço de limpeza de calhas', 'Fornecedor de calhas', 'Empreiteiro de telhados',), None),
    ('pisos', 'PISOS', ('Empreiteiro de pisos', 'Loja de pisos', 'Serviço de instalação de piso de madeira', 'Loja de pisos de madeira', 'Fornecedor de piso laminado',), None),
    ('marmoraria', 'MARMORARIA', ('Marmoraria', 'Fornecedor de granito', 'Fornecedor de mármore', 'Fabricante de pedra', 'Fornecedor de pedra', 'Loja de bancadas',), None),
    ('pedreiro_alvenaria', 'PEDREIRO / ALVENARIA', ('Pedreiro', 'Empreiteiro de alvenaria', 'Empreiteiro', 'Empreiteiro geral',), None),
    ('carpintaria', 'CARPINTARIA', ('Carpinteiro', 'Empreiteiro de carpintaria', 'Marceneiro',), None),
    ('paisagismo', 'PAISAGISMO', ('Paisagista', 'Empresa de paisagismo', 'Designer de paisagem', 'Jardineiro', 'Serviço de jardinagem',), None),
    ('jardinagem', 'JARDINAGEM', ('Jardineiro', 'Serviço de jardinagem', 'Paisagista', 'Empresa de paisagismo',), None),
    ('piscinas', 'PISCINAS', ('Empreiteiro de piscinas', 'Construtor de piscinas', 'Serviço de limpeza de piscinas', 'Serviço de manutenção de piscinas', 'Loja de piscinas', 'Fornecedor de equipamentos para piscinas',), None),
    ('toldos_coberturas', 'TOLDOS / COBERTURAS', ('Fornecedor de toldos', 'Loja de toldos', 'Empreiteiro de coberturas', 'Fornecedor de coberturas',), None),
    ('persianas_cortinas', 'PERSIANAS / CORTINAS', ('Loja de persianas', 'Loja de cortinas', 'Loja de tratamento de janelas', 'Fornecedor de persianas',), None),
    ('automacao_residencial', 'AUTOMAÇÃO RESIDENCIAL', ('Empresa de automação residencial', 'Fornecedor de sistemas de automação', 'Consultor de automação',), None),
    ('seguranca_eletronica', 'SEGURANÇA ELETRÔNICA', ('Fornecedor de sistema de segurança', 'Serviço de segurança', 'Empresa de sistemas de segurança', 'Fornecedor de alarmes', 'Serviço de instalação de segurança',), None),
    ('cameras_de_seguranca', 'CÂMERAS DE SEGURANÇA', ('Fornecedor de sistema de segurança', 'Loja de câmeras', 'Empresa de sistemas de segurança',), None),
    ('portoes_automaticos', 'PORTÕES AUTOMÁTICOS', ('Fornecedor de portas de garagem', 'Serviço de conserto de portas de garagem', 'Fornecedor de portões', 'Serralheiro',), None),
    ('chaveiro', 'CHAVEIRO', ('Chaveiro', 'Serviço de chaveiro', 'Loja de fechaduras',), None),
    ('mudancas', 'MUDANÇAS', ('Empresa de mudanças', 'Serviço de mudanças', 'Serviço de mudança e armazenamento', 'Empresa de transporte',), None),
    ('fretes', 'FRETES', ('Serviço de frete', 'Empresa de transporte', 'Serviço de transporte', 'Transportadora',), None),
    ('guincho', 'GUINCHO', ('Serviço de reboque', 'Empresa de reboque', 'Serviço de assistência automotiva',), None),
    ('oficina_mecanica', 'OFICINA MECÂNICA', ('Oficina mecânica', 'Mecânico', 'Serviço de reparação de automóveis', 'Centro automotivo', 'Oficina de automóveis',), None),
    ('oficina_de_motos', 'OFICINA DE MOTOS', ('Oficina de motocicletas', 'Serviço de conserto de motocicletas', 'Concessionária de motocicletas', 'Loja de peças para motocicletas',), None),
    ('autoeletrica', 'AUTOELÉTRICA', ('Autoelétrico', 'Serviço de reparos elétricos automotivos', 'Oficina mecânica',), None),
    ('funilaria_e_pintura', 'FUNILARIA E PINTURA', ('Oficina de funilaria', 'Oficina de pintura automotiva', 'Serviço de reparação de automóveis', 'Oficina de automóveis',), None),
    ('estetica_automotiva', 'ESTÉTICA AUTOMOTIVA', ('Serviço de detalhamento automotivo', 'Lava-rápido', 'Lavagem de carros', 'Serviço de restauração de automóveis',), None),
    ('insulfilm', 'INSULFILM', ('Serviço de instalação de películas', 'Loja de películas para vidros', 'Loja de acessórios automotivos',), None),
    ('som_acessorios_automotivos', 'SOM / ACESSÓRIOS AUTOMOTIVOS', ('Loja de som automotivo', 'Loja de acessórios automotivos', 'Loja de eletrônicos automotivos',), None),
    ('fotografia', 'FOTOGRAFIA', ('Fotógrafo', 'Estúdio fotográfico', 'Fotógrafo de casamento', 'Fotógrafo de eventos', 'Fotógrafo comercial',), None),
    ('video_produtora', 'VÍDEO / PRODUTORA', ('Produtora de vídeo', 'Serviço de produção de vídeo', 'Empresa de produção de mídia', 'Fotógrafo de vídeo',), None),
    ('buffet_eventos', 'BUFFET / EVENTOS', ('Serviço de buffet', 'Empresa de eventos', 'Organizador de eventos', 'Salão de eventos', 'Serviço de festas',), None),
    ('decoracao_de_festas', 'DECORAÇÃO DE FESTAS', ('Decorador de eventos', 'Empresa de eventos', 'Organizador de eventos', 'Loja de artigos para festas',), None),
    ('casamentos_cerimonial', 'CASAMENTOS / CERIMONIAL', ('Organizador de casamentos', 'Cerimonialista', 'Organizador de eventos', 'Serviço de casamento',), None),
    ('dj', 'DJ', ('DJ', 'Serviço de DJ', 'Empresa de entretenimento',), None),
    ('informatica', 'INFORMÁTICA', ('Serviço de informática', 'Serviço de conserto de computadores', 'Assistência técnica de computadores', 'Consultor de informática', 'Loja de informática',), None),
    ('assistencia_de_celular', 'ASSISTÊNCIA DE CELULAR', ('Serviço de conserto de celulares', 'Loja de conserto de celulares', 'Loja de celulares',), None),
    ('contabilidade', 'CONTABILIDADE', ('Contador', 'Escritório de contabilidade', 'Empresa de contabilidade', 'Serviço de contabilidade', 'Consultor tributário',), None),
    ('advocacia', 'ADVOCACIA', ('Advogado', 'Escritório de advocacia', 'Advogado civil', 'Advogado trabalhista', 'Advogado empresarial', 'Advogado de direito de família', 'Advogado imobiliário', 'Advogado criminalista', 'Advogado previdenciário',), None),
    ('imobiliaria', 'IMOBILIÁRIA', ('Imobiliária', 'Agência imobiliária', 'Corretor de imóveis', 'Consultor imobiliário', 'Empresa de administração de imóveis', 'Empresa de gestão de propriedades',), None),
    ('seguros', 'SEGUROS', ('Corretor de seguros', 'Agência de seguros', 'Companhia de seguros', 'Consultor de seguros',), None),
    ('arquitetura', 'ARQUITETURA', ('Arquiteto', 'Escritório de arquitetura', 'Designer de arquitetura', 'Empresa de arquitetura',), None),
    ('design_de_interiores', 'DESIGN DE INTERIORES', ('Designer de interiores', 'Empresa de design de interiores', 'Decorador de interiores',), None),
    ('engenharia_civil', 'ENGENHARIA CIVIL', ('Engenheiro civil', 'Empresa de engenharia civil', 'Consultor de engenharia', 'Empresa de engenharia',), None),
    ('topografia', 'TOPOGRAFIA', ('Topógrafo', 'Empresa de topografia', 'Engenheiro agrimensor',), None),
    ('clinica_de_estetica', 'CLÍNICA DE ESTÉTICA', ('Clínica de estética', 'Esteticista', 'Spa facial', 'Spa', 'Centro de estética', 'Clínica de cuidados com a pele',), None),
    ('depilacao_a_laser', 'DEPILAÇÃO A LASER', ('Serviço de depilação a laser', 'Clínica de depilação a laser', 'Centro de depilação',), None),
    ('massoterapia', 'MASSOTERAPIA', ('Massoterapeuta', 'Massagista', 'Spa de massagens', 'Clínica de massagem',), None),
    ('quiropraxia', 'QUIROPRAXIA', ('Quiroprático', 'Clínica de quiropraxia', 'Centro de bem-estar',), None),
    ('fisioterapia', 'FISIOTERAPIA', ('Fisioterapeuta', 'Clínica de fisioterapia', 'Centro de reabilitação', 'Clínica de medicina esportiva',), None),
    ('odontologia', 'ODONTOLOGIA', ('Dentista', 'Clínica odontológica', 'Dentista cosmético', 'Ortodontista', 'Periodontista', 'Endodontista', 'Implantodontista', 'Cirurgião-dentista', 'Odontopediatra',), None),
    ('psicologia', 'PSICOLOGIA', ('Psicólogo', 'Clínica de psicologia', 'Psicoterapeuta', 'Serviço de saúde mental',), None),
    ('nutricao', 'NUTRIÇÃO', ('Nutricionista', 'Consultor de saúde', 'Clínica de nutrição',), None),
    ('personal_trainer', 'PERSONAL TRAINER', ('Personal trainer', 'Academia', 'Centro de condicionamento físico',), None),
    ('pilates', 'PILATES', ('Estúdio de pilates', 'Instrutor de pilates', 'Centro de condicionamento físico',), None),
    ('barber_shop', 'BARBEARIA', ('Barbearia', 'Barbeiro',), 'barber_shop'),
    ('beauty_salon', 'SALÃO DE BELEZA', ('Salão de beleza', 'Cabeleireiro', 'Salão de cabeleireiro', 'Especialista em extensões de cabelo',), 'beauty_salon'),
    ('nail_salon', 'MANICURE', ('Salão de manicure', 'Manicure', 'Nail designer', 'Salão de beleza',), 'nail_salon'),
    ('podologia', 'PODOLOGIA', ('Podólogo', 'Clínica de podologia', 'Serviço de cuidados com os pés',), None),
    ('tatuagem', 'TATUAGEM', ('Estúdio de tatuagem', 'Tatuador', 'Serviço de tatuagem',), None),
    ('adestramento_de_caes', 'ADESTRAMENTO DE CÃES', ('Adestrador de cães', 'Treinador de cães', 'Serviço de adestramento de animais',), None),
    ('hotel_creche_para_caes', 'HOTEL / CRECHE PARA CÃES', ('Hotel para cães', 'Serviço de hospedagem para animais', 'Creche para cães', 'Pet sitter', 'Serviço de cuidados para animais',), None),
    ('banho_e_tosa', 'BANHO E TOSA', ('Pet shop', 'Banho e tosa', 'Tosador', 'Serviço de cuidados para animais',), None),
    ('veterinary_care', 'VETERINÁRIA', ('Veterinário', 'Clínica veterinária', 'Hospital veterinário', 'Serviço veterinário de emergência',), 'veterinary_care'),
    ('laundry', 'LAVANDERIA', ('Lavanderia', 'Lavanderia a seco', 'Serviço de lavanderia', 'Lavanderia automática',), 'laundry'),
    ('conserto_de_eletrodomesticos', 'CONSERTO DE ELETRODOMÉSTICOS', ('Serviço de conserto de eletrodomésticos', 'Assistência técnica de eletrodomésticos', 'Serviço de conserto de refrigeradores', 'Serviço de conserto de lavadoras', 'Serviço de reparação de equipamentos',), None),
    ('manutencao_predial', 'MANUTENÇÃO PREDIAL', ('Serviço de manutenção predial', 'Manutenção de propriedade', 'Empresa de administração de propriedades', 'Faz-tudo', 'Empreiteiro geral',), None),
    ('limpeza_de_fachadas', 'LIMPEZA DE FACHADAS', ('Serviço de limpeza', 'Serviço de limpeza de janelas', 'Serviço de limpeza comercial', 'Serviço de lavagem sob pressão',), None),
    ('limpeza_de_caixa_d_agua', "LIMPEZA DE CAIXA D'ÁGUA", ('Serviço de limpeza', 'Serviço de saneamento', 'Empresa de limpeza',), None),
    ('perfuracao_de_pocos', 'PERFURAÇÃO DE POÇOS', ('Empreiteiro de perfuração de poços', 'Empresa de perfuração', 'Serviço de perfuração',), None),
    ('terraplenagem', 'TERRAPLENAGEM', ('Empreiteiro de terraplenagem', 'Empreiteiro de escavação', 'Empresa de terraplenagem', 'Empreiteiro',), None),
    ('demolicao', 'DEMOLIÇÃO', ('Empreiteiro de demolição', 'Empresa de demolição', 'Empreiteiro',), None),
    ('cacambas', 'CAÇAMBAS', ('Serviço de aluguel de caçambas', 'Serviço de coleta de lixo', 'Empresa de gestão de resíduos', 'Serviço de remoção de entulho',), None),
    ('concreto', 'CONCRETO', ('Empreiteiro de concreto', 'Fornecedor de concreto pronto', 'Empresa de concretagem', 'Fornecedor de concreto',), None),
    ('instalacao_de_gas', 'INSTALAÇÃO DE GÁS', ('Empresa de instalação de gás', 'Instalador de gás', 'Encanador', 'Empreiteiro de aquecimento',), None),
    ('aquecedor_a_gas', 'AQUECEDOR A GÁS', ('Serviço de conserto de aquecedores', 'Fornecedor de aquecedores', 'Empreiteiro de aquecimento', 'Encanador',), None),
    ('tapecaria_reforma_de_estofados', 'TAPEÇARIA / REFORMA DE ESTOFADOS', ('Tapeceiro', 'Loja de estofados', 'Oficina de conserto de móveis', 'Serviço de restauração de móveis',), None),
)
